import { Manrope } from "next/font/google";
import Favicon from "/public/images/favicon.ico";
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });
const font = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Oscar Loaiza | Web Developer",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({ children }) {
  return (
    <html
      className="scrollbar-w-8 scrollbar-track-rounded-full scrollbar scrollbar-thumb-new-950 scrollbar-track-new-500 h-32 overflow-y-scroll"
      lang="es"
    >
      <body
        className={`${font.className} transition-all animate-[appear_1500ms_cubic-bezier(0.4,_0,_0.2,_1)_100ms_backwards]`}
      >
        {children}
      </body>
    </html>
  );
}
